### ISSUE TITLE
What is the pupose of timer when building database?

### ISSUE THREAD

**Issue by KrystofS** [blakeb211/HoldemPokerTrainer#2]
Hi,
I know you´re done with the project, but hopefully you´ll answer regardless. What is the purpose of the 2 minute timer when building new database?

Also on a unrelated topic just to be clear, database size doesn´t really scale with number of games, right?

**Comment by blakeb211** [comment]
For the database growing, once all possible combinations of cards have been hit at least once the database should peak in size, and then not grow much more. So at first it scales and then should plateau.

For the timer question, yes I remember. There is one thread writing the game data to disk and multiple threads generating the game data. The data is generated *faster* than it is written, so it starts to accumulate. There is a timer that lets the writing thread work by itself to store those accumulated games and get them out of RAM.  Basically I want there to always be games that the writing thread can write so its stays 100% active all the time, but I don't want the game-data-generating threads to be too far ahead of the writing thread.

**Comment by KrystofS** [comment]
Thanks, but I think we´re talking about different timers. I think you´re mentioning timer on line 109. I should´ve been clearer that I meant timer on line 67 in the same file (Simulation.cs). It´s what you mention in readme. Could you clarify that one?

**Comment by blakeb211** [comment]
The timer on line 67 is inside of a while(true) loop that prevents the main thread from ending while the recordProducer and recordConsumer threads are still running. We want the main function to print the duration data at the end so we need to keep it open.  If there was no timer, that loop would be constantly checking whether the threads had ended, likely both burning cpu and bogging the rest of the threads down. Also non-blocking pause tells the OS scheduler to focus on the other threads so that they can get more CPU time
